<?php
declare(strict_types=1);
/**
 * This file is part of EasySwoole.
 *
 * @link     https://www.easyswoole.com
 * @document https://www.easyswoole.com
 * @contact  https://www.easyswoole.com/Preface/contact.html
 * @license  https://github.com/easy-swoole/easyswoole/blob/3.x/LICENSE
 */

namespace EasySwoole\VerifyCode\Test;

use EasySwoole\VerifyCode\Config;
use PHPUnit\Framework\TestCase;
use EasySwoole\VerifyCode\VerifyCode;

class VerifyCodeTest extends TestCase
{
    protected function setUp(): void
    {
        error_reporting(E_ALL);
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testDrawCode()
    {
        // 配置验证码
        $config = new Config();
        $code = new VerifyCode($config);

        // 生成验证码
        $captchaCode = 'Ornh';
        $drawCode = $code->DrawCode('Ornh');
        $codeStr = $drawCode->getImageCode();

        $this->assertSame($captchaCode, $codeStr);

        $filename = __DIR__ . "/{$captchaCode}.png";
        $mime = 'image/png';
        if (function_exists('mime_content_type')) {
            file_put_contents($filename, $drawCode->getImageByte());
            $this->assertSame($mime, mime_content_type($filename));
            unlink($filename);
        }

        $startsWith = "data:{$mime};base64,";
        $imgBase64 = $drawCode->getImageBase64();
        $this->assertStringStartsWith($startsWith, $imgBase64);

        $imgByte = base64_decode(str_replace($startsWith, '', $imgBase64));
        $this->assertSame($drawCode->getImageByte(), $imgByte);
    }
}
